title: SMS Speedrunning Notes
description: RTA Notes made by spilledBeansEverywhere
theme: just-the-docs

url: https://spilledBeansEverywhere.github.io/sms-speedrunning-guide

aux_links:
  Template Repository: https://github.com/emrik542/sms-speedrunning-notes
