title: SMS Speedrunning Notes
description: RTA Notes made by spilledBeansEverywhere
theme: just-the-docs

url: https://spilledBeansEverywhere.github.io/sms-speedrunning-notes

aux_links:
  Template Repository: https://github.com/spilledBeansEverywhere/sms-speedrunning-notes
